- name: Setup macOS
  hosts: localhost
  tasks:
    - block:
        - import_tasks: tasks/customization.yaml
          tags: customization

        - import_tasks: tasks/1password.yaml
          tags: 1password

        - import_tasks: tasks/ssh.yaml
          tags: ssh

        - import_tasks: tasks/terminal.yaml
          tags: terminal

        - import_tasks: tasks/zsh.yaml
          tags: zsh

        - import_tasks: tasks/productivity.yaml
          tags: productivity

        - import_tasks: tasks/neovim.yaml
          tags: neovim

        - import_tasks: tasks/vscode.yaml
          tags: vscode

        - import_tasks: tasks/node.yaml
          tags: node

        - import_tasks: tasks/docker.yaml
          tags: docker

        - import_tasks: tasks/aerospace.yaml
          tags: aerospace

        - import_tasks: tasks/hammerspoon.yaml
          tags: hammerspoon

        - import_tasks: tasks/flameshot.yaml
          tags: flameshot

        - import_tasks: tasks/discord.yaml
          tags: discord

        - import_tasks: tasks/google-chrome.yaml
          tags: google-chrome

        - import_tasks: tasks/localsend.yaml
          tags: localsend

        - import_tasks: tasks/spotify.yaml
          tags: spotify

      when: ansible_os_family == 'Darwin'
