- name: Install 1Password Desktop
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: 1password

- name: Install 1Password CLI
  homebrew:
    name: 1password-cli

# Fix this because it's not working as expected

- name: Check if user is already signed in to 1Password
  shell: op whoami
  register: op_cli_integrated
  ignore_errors: true

- pause:
    prompt: Turn on the 1Password desktop app integration (https://developer.1password.com/docs/cli/get-started/#step-2-turn-on-the-1password-desktop-app-integration)
  when: op_cli_integrated.rc != 0
