- name: Create and/or update bashrc_local_before
  blockinfile:
    path: ~/.bashrc_local_before
    block: |
      [ -d "$OSWEAVER_DIR/dotfiles/macos/bin" ] && path_prepend "$OSWEAVER_DIR/dotfiles/macos/bin"

      [ -f /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash ] &&
          . /Library/Developer/CommandLineTools/usr/share/git-core/git-completion.bash

      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
    create: yes

- name: Create and/or update bashrc_local_after
  blockinfile:
    path: ~/.bashrc_local_after
    block: |
      $(brew --prefix)/opt/fzf/install --all >/dev/null
      [ -f ~/.fzf.bash ] && source ~/.fzf.bash    # for bash
    create: yes
