- name: Install Rosetta (allow run Intel based code)
  shell: softwareupdate --install-rosetta --agree-to-license

- name: Install flameshot
  homebrew_cask:
    name: flameshot

- name: Open flameshot
  shell: open /Applications/flameshot.app

- pause:
    prompt: Allow flameshot on System Settings

- name: Run flameshot on startup
  shell: /Applications/flameshot.app/Contents/MacOS/flameshot config --autostart true
