- name: Create and/or update gitconfig_local
  blockinfile:
    path: ~/.gitconfig_local
    block: |
      [user]
      name = Leonardo Rodrigues Ferreira
      email = leorodriguesf95@gmail.com

      [alias]
      g = log --all --graph --oneline
      s = status --short
    create: yes
