- name: Add zsh-autosuggestions
  homebrew:
    name: zsh-autosuggestions

- name: Get whoami to change its default shell
  shell: whoami
  register: user

- name: Change default shell
  become: true
  shell: sudo chsh -s /bin/zsh {{user.stdout}}
