- name: Update gitconfig
  blockinfile:
    path: ~/.gitconfig_local
    block: |
      [includeIf "gitdir:~/work/"]
      path = ~/.gitconfig_work
    create: yes

- name: Add git config for work
  copy:
    src: "{{ lookup('env', 'OSWEAVER_DIR') }}/dotfiles/work/git/gitconfig"
    dest: ~/.gitconfig_work
    mode: 0600
    force: true
