- name: Add node certificates
  blockinfile:
    path: ~/.shell_local_before
    block: |
      export NODE_OPTIONS=--max-old-space-size=8192
      export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
    create: yes
