- name: Add node certificates
  blockinfile:
    path: ~/.shell_local_before
    block: |
      export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
      export NODE_OPTIONS=--max_old_space_size=10240
    create: yes
